---

- name: Add Percona official RPM repository
  tags: [ pmm, pmm-client, percona-release-upgrade ]
  yum:
    name: "https://repo.percona.com/yum/percona-release-{{ percona_release_version }}.noarch.rpm"
    allow_downgrade: yes
    state: present

- name: Upgrade yum cache
  tags: [ pmm, pmm-client, pmm-client-upgrade, pmm-client-upgrade]
  yum:
    update_cache: yes

- name: Install pmm2-client
  tags: [ pmm, pmm-client, pmm-client-upgrade, pmm-client-upgrade ]
  yum:
    name: "pmm2-client-{{ pmm_client_version }}"
    allow_downgrade: yes
    state: present
