---

- name: Include validate.yml
  tags: [ pmm, pmm-client, validate, pmm-validate, pmm-client-validate ]
  include: validate.yml

- name: Include procedures.yml
  tags: [ pmm, pmm-client, monitor-scripts-upgrade ]
  include: validate.yml

- name: Include install.yml
  tags: [ pmm, pmm-client, percona-release-upgrade, pmm-client-upgrade ]
  include: validate.yml

- name: Include configure.yml
  tags: [ pmm, pmm-client, pmm-client-configure, pmm-client-upgrade ]
  include: validate.yml
