---

- name: Create directory for monitoring scripts
  tags: [ pmm, pmm-client, monitor-scripts-upgrade ]
  file:
    path: "{{ monitoring_scripts_dir }}"
    mode: '0775'
    state: directory

- name: Upload PMM stored procedures SQL files
  tags: [ pmm, pmm-client, monitor-scripts-upgrade ]
  template:
    src: ./templates/*
    dest:  "{{ monitoring_scripts_dir }}"
    mode: '0775'
    state: present

- name: Create MariaDB stored procedures to setup PMM
  tags: [ pmm, pmm-client, monitor-scripts-upgrade ]
  shell: >
    mysql <  -u"{{ admin_mariadb_user }}" -p"{{ admin_mariadb_password }}" "{{ monitoring_scripts_dir }}"/pmm_client_setup.sql

- name: Test MariaDB stored procedures
  tags: [ pmm, pmm-client, monitor-scripts-upgrade ]
  shell: >
    mysql <  -u"{{ admin_mariadb_user }}" -p"{{ admin_mariadb_password }}" "{{ monitoring_scripts_dir }}"/test_pmm_client_setup.sql
  when: skip_stored_procedures_test != '1'

- name: Call vettabase.create_pmm_user()
  tags: [ pmm, pmm-client, monitor-scripts-upgrade ]
  shell: >
    "mysql -u{{ admin_mariadb_user }} -p{{ admin_mariadb_password }} -e 'CALL vettabase.create_pmm_user({{ pmm_mariadb_username }}, {{ pmm_server_host }}, {{ pmm_mariadb_username }}, {{ pmm_mariadb_password }})'"
